import React, { useEffect, useState } from 'react';
import reportService from '../services/reportService';
import DataTable from '../components/DataTable';
import Modal from '../components/Modal';
import Button from '../components/Button';
import { useAuth } from '../context/AuthContext';

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

export default function Reports() {
  const { isAdmin, isSuperAdmin } = useAuth();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [modalOpen, setModalOpen] = useState(false);
  const [error, setError] = useState('');
  const [generating, setGenerating] = useState(false);

  const now = new Date();
  const [form, setForm] = useState({
    month: now.getMonth() + 1,
    year: now.getFullYear(),
    notes: '',
  });

  const loadReports = () => {
    setLoading(true);
    reportService
      .getAll()
      .then((data) => setReports(data.sort((a, b) => (b.year - a.year) || (b.month - a.month))))
      .catch(() => setError('Failed to load reports.'))
      .finally(() => setLoading(false));
  };

  useEffect(loadReports, []);

  const handleChange = (e) => {
    setForm((prev) => ({ ...prev, [e.target.name]: e.target.value }));
  };

  const handleGenerate = async (e) => {
    e.preventDefault();
    setGenerating(true);
    setError('');
    try {
      await reportService.generate(Number(form.month), Number(form.year), form.notes);
      setModalOpen(false);
      loadReports();
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to generate report.');
    } finally {
      setGenerating(false);
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Delete this report?')) return;
    try {
      await reportService.remove(id);
      loadReports();
    } catch {
      alert('Failed to delete report.');
    }
  };

  const columns = [
    { key: 'period', label: 'Period', render: (row) => `${MONTH_NAMES[row.month - 1]} ${row.year}` },
    {
      key: 'totalCollectedQty',
      label: 'Collected (Tons)',
      render: (row) => (row.totalCollectedQty ?? 0).toLocaleString(),
    },
    {
      key: 'totalDisposedQty',
      label: 'Disposed (Tons)',
      render: (row) => (row.totalDisposedQty ?? 0).toLocaleString(),
    },
    { key: 'incidentsCount', label: 'Incidents' },
    { key: 'generatedBy', label: 'Generated By' },
    {
      key: 'generatedAt',
      label: 'Generated At',
      render: (row) => (row.generatedAt ? new Date(row.generatedAt).toLocaleString() : '—'),
    },
  ];

  return (
    <div>
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.25rem' }}>
        <div>
          <h2 style={{ margin: 0 }}>Monthly Reports</h2>
          <p style={{ color: 'var(--color-text-muted)', margin: '0.3rem 0 0' }}>
            Aggregated collection, disposal and incident figures by month.
          </p>
        </div>
        {!isSuperAdmin && (
          <Button onClick={() => { setError(''); setModalOpen(true); }}>+ Generate Report</Button>
        )}
      </div>

      <DataTable
        columns={columns}
        data={reports}
        loading={loading}
        emptyMessage="No reports generated yet."
        actions={(row) => (
          isAdmin && (
            <Button size="sm" variant="danger" onClick={() => handleDelete(row.id)}>Delete</Button>
          )
        )}
      />

      <Modal
        isOpen={modalOpen}
        onClose={() => setModalOpen(false)}
        title="Generate Monthly Report"
        footer={
          <>
            <Button variant="ghost" onClick={() => setModalOpen(false)}>Cancel</Button>
            <Button onClick={handleGenerate} disabled={generating}>
              {generating ? 'Generating…' : 'Generate'}
            </Button>
          </>
        }
      >
        <form onSubmit={handleGenerate}>
          <p style={{ fontSize: '0.85rem', color: 'var(--color-text-muted)', marginTop: 0 }}>
            This will calculate totals from existing collection, disposal and incident
            records for the selected month. Re-generating an existing period will refresh
            its figures.
          </p>
          <div className="form-row" style={{ display: 'flex', gap: '0.75rem' }}>
            <Field label="Month">
              <select name="month" value={form.month} onChange={handleChange} style={inputStyle}>
                {MONTH_NAMES.map((name, idx) => (
                  <option key={name} value={idx + 1}>{name}</option>
                ))}
              </select>
            </Field>
            <Field label="Year">
              <input
                name="year"
                type="number"
                value={form.year}
                onChange={handleChange}
                style={inputStyle}
                min="2000"
                max="2100"
              />
            </Field>
          </div>
          <Field label="Notes (optional)">
            <textarea
              name="notes"
              value={form.notes}
              onChange={handleChange}
              rows={3}
              style={{ ...inputStyle, resize: 'vertical' }}
            />
          </Field>
          {error && <div style={{ color: 'var(--color-danger)', fontSize: '0.85rem' }}>{error}</div>}
        </form>
      </Modal>
    </div>
  );
}

function Field({ label, children }) {
  return (
    <div style={{ marginBottom: '0.9rem', flex: 1 }}>
      <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: 600, marginBottom: '0.3rem' }}>{label}</label>
      {children}
    </div>
  );
}

const inputStyle = {
  width: '100%',
  padding: '0.5rem 0.65rem',
  border: '1px solid var(--color-border)',
  borderRadius: 'var(--radius)',
  fontSize: '0.88rem',
};
